import SwiftUI
import SwiftUIFastCharts

/// Small progress-rate sparkline tile inside the grid (the big
/// version, if/when reinstated, lives in the upper section).
/// Two series — self-play / training — on a shared Y axis, with the
/// moves/hour readout in the chart's own header. The combined
/// (sp + train) line was removed because the two component lines
/// already convey the throughput story and the sum was visual noise.
struct SmallProgressRateChart: View {
    let buckets: [ProgressRateBucket]
    let group: FastChartGroup
    let xDomain: ClosedRange<Double>
    let bucketWidthSec: Double

    private static let selfPlayColor: Color = .blue
    private static let trainingColor: Color = .orange

    var body: some View {
        FastLineChart(
            title: "Progress rate (self play + train)",
            titleHelp: AttributedString("""
                Throughput in moves per hour. Self-play (blue) is positions generated by the \
                workers; training (orange) is positions consumed by the trainer. Training rate \
                should track self-play rate × the configured replay ratio.
                """),
            group: group,
            xDomain: xDomain,
            yDomain: 0...yMaxObserved(),
            series: [
                FastChartSeries(
                    id: "Self-play",
                    color: Self.selfPlayColor,
                    lineWidth: 1.5,
                    data: .buckets(buckets.enumerated().map { (i, b) in
                        FastChartBucket(
                            id: i,
                            x: b.elapsedSec,
                            yMin: b.selfPlayMovesPerHour?.min ?? .nan,
                            yMax: b.selfPlayMovesPerHour?.max ?? .nan
                        )
                    })
                ),
                FastChartSeries(
                    id: "Training",
                    color: Self.trainingColor,
                    lineWidth: 1.5,
                    data: .buckets(buckets.enumerated().map { (i, b) in
                        FastChartBucket(
                            id: i,
                            x: b.elapsedSec,
                            yMin: b.trainingMovesPerHour?.min ?? .nan,
                            yMax: b.trainingMovesPerHour?.max ?? .nan
                        )
                    })
                )
            ],
            legend: .off,
            headerValue: { ctx in headerString(at: ctx.hoveredX) }
        )
        .frame(height: 75)
        .chartCard()
    }

    private func yMaxObserved() -> Double {
        let b = buckets.compactMap { $0.selfPlayMovesPerHour?.max }.max() ?? 0
        let c = buckets.compactMap { $0.trainingMovesPerHour?.max }.max() ?? 0
        let m = Swift.max(b, c)
        return Swift.max(m * 1.1, 10)
    }

    private func headerString(at hoveredX: Double?) -> AttributedString {
        let tolerance = Swift.max(
            TrainingChartGridView.hoverMatchToleranceSec,
            bucketWidthSec * 1.5
        )
        if let t = hoveredX {
            if let nearest = TrainingChartGridView.nearestProgressBucket(
                at: t, in: buckets, tolerance: tolerance
            ) {
                let selfPlay = nearest.selfPlayMovesPerHour?.max ?? 0
                let training = nearest.trainingMovesPerHour?.max ?? 0
                var out = AttributedString("")
                var spPart = AttributedString(
                    "sp=\(FastChartFormatters.compact(selfPlay))"
                )
                spPart.foregroundColor = Self.selfPlayColor
                out.append(spPart)
                out.append(AttributedString(" "))
                var trPart = AttributedString(
                    "tr=\(FastChartFormatters.compact(training))"
                )
                trPart.foregroundColor = Self.trainingColor
                out.append(trPart)
                return out
            }
            return AttributedString("— no data")
        }
        if let last = buckets.last,
           let selfPlay = last.selfPlayMovesPerHour?.max {
            return AttributedString("\(FastChartFormatters.compact(selfPlay)) moves/hour (sp)")
        }
        return AttributedString("-- moves/hour")
    }
}

extension SmallProgressRateChart: Equatable {
    nonisolated static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.bucketWidthSec == rhs.bucketWidthSec
            && lhs.xDomain == rhs.xDomain
            && lhs.group === rhs.group
            && lhs.buckets == rhs.buckets
    }
}
