// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build (Run Script phase before Compile Sources).
enum BuildInfo {
    static let buildNumber = 1578
    static let buildDate = "2026-06-02"
    static let buildTimestamp = "2026-06-02T11:25:05-0500"
    static let gitHash = "299eabf"
    static let gitBranch = "bf16-trainer"
    static let gitDirty = true

    /// One-line human-readable summary, e.g. "build 237 (abc1234*) 2026-04-17".
    /// Asterisk suffix on gitHash indicates a dirty working tree at build time.
    static var summary: String {
        let dirtyMarker = gitDirty ? "*" : ""
        return "build \(buildNumber) (\(gitHash)\(dirtyMarker)) \(buildDate)"
    }
}
