// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build (Run Script phase before Compile Sources).
enum BuildInfo {
    static let buildNumber = 2358
    static let buildDate = "2026-10-06"
    static let buildTimestamp = "2026-10-06T19:37:20-0500"
    static let gitHash = "92c71a1c"
    static let gitBranch = "worktree-agent-a3b6ce12b50064967"
    /// Whether the compiled project (`DrewsChessMachine/`, without this
    /// file and the build counter) differed from `gitHash` at build time.
    static let gitDirty = true
    /// SHA-256 of the uncommitted changes under that scope (tracked diff
    /// plus framed untracked files); nil exactly when `gitDirty` is false.
    static let gitDiffSHA256: String? = "72f92869c01c7b13d2a23b5b7d2d83fff9e9f87d3446f1df21f19ec5abac4032"
    /// Xcode's build version (`XCODE_PRODUCT_BUILD_VERSION`).
    static let xcodeBuild = "27A9269"
    /// The SDK's build version (`SDK_PRODUCT_BUILD_VERSION`).
    static let sdkBuild = "26A425"
    /// The build configuration (`CONFIGURATION`), e.g. Debug or Release.
    static let configuration = "Debug"

    /// One-line human-readable summary, e.g. "build 237 (abc1234*) 2026-04-17".
    /// Asterisk suffix on gitHash indicates a dirty working tree at build time.
    static var summary: String {
        let dirtyMarker = gitDirty ? "*" : ""
        return "build \(buildNumber) (\(gitHash)\(dirtyMarker)) \(buildDate)"
    }
}
