#!/bin/bash
# Generates BuildInfo.swift with the current git commit count and date.
# Called as an Xcode Run Script build phase (before Compile Sources).
# The output lands in the source folder so the file-system-synchronized
# group picks it up automatically.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$SCRIPT_DIR/DrewsChessMachine/BuildInfo.swift"
REPO_ROOT="$SCRIPT_DIR/.."

BUILD_NUM=$(git -C "$REPO_ROOT" rev-list --count HEAD 2>/dev/null || echo "0")
BUILD_DATE=$(date +%Y-%m-%d)
GIT_HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$OUTPUT" << EOF
// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build.
enum BuildInfo {
    static let buildNumber = $BUILD_NUM
    static let buildDate = "$BUILD_DATE"
    static let gitHash = "$GIT_HASH"
}
EOF
