#!/bin/bash
# Generates BuildInfo.swift with a monotonic per-build counter plus
# current commit metadata. Invoked as an Xcode Run Script build phase
# that runs BEFORE the Compile Sources phase, with `alwaysOutOfDate`
# set so every build (including incremental ones) bumps the counter.
#
# The counter lives at `DrewsChessMachine/build_counter.txt` next to
# this script. If it's missing on first run, it seeds from the repo's
# commit count so the number stays close to prior committed builds.
# The file is intentionally cheap to ignore if the developer doesn't
# want it committed — edit .gitignore locally.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$SCRIPT_DIR/DrewsChessMachine/BuildInfo.swift"
COUNTER="$SCRIPT_DIR/build_counter.txt"
REPO_ROOT="$SCRIPT_DIR/.."

if [ -f "$COUNTER" ]; then
    CURRENT=$(cat "$COUNTER" 2>/dev/null || echo "0")
    case "$CURRENT" in
        ''|*[!0-9]*) CURRENT=0 ;;
    esac
    BUILD_NUM=$((CURRENT + 1))
else
    BUILD_NUM=$(git -C "$REPO_ROOT" rev-list --count HEAD 2>/dev/null || echo "0")
    BUILD_NUM=$((BUILD_NUM + 1))
fi
echo "$BUILD_NUM" > "$COUNTER"

BUILD_DATE=$(date +%Y-%m-%d)
BUILD_TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S%z")
GIT_HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
if ! git -C "$REPO_ROOT" diff --quiet 2>/dev/null || ! git -C "$REPO_ROOT" diff --cached --quiet 2>/dev/null; then
    GIT_DIRTY="true"
else
    GIT_DIRTY="false"
fi

cat > "$OUTPUT" << EOF
// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build (Run Script phase before Compile Sources).
enum BuildInfo {
    static let buildNumber = $BUILD_NUM
    static let buildDate = "$BUILD_DATE"
    static let buildTimestamp = "$BUILD_TIMESTAMP"
    static let gitHash = "$GIT_HASH"
    static let gitBranch = "$GIT_BRANCH"
    static let gitDirty = $GIT_DIRTY

    /// One-line human-readable summary, e.g. "build 237 (abc1234*) 2026-04-17".
    /// Asterisk suffix on gitHash indicates a dirty working tree at build time.
    static var summary: String {
        let dirtyMarker = gitDirty ? "*" : ""
        return "build \(buildNumber) (\(gitHash)\(dirtyMarker)) \(buildDate)"
    }
}
EOF
