// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build (Run Script phase before Compile Sources).
enum BuildInfo {
    static let buildNumber = 101
    static let buildDate = "2026-04-18"
    static let buildTimestamp = "2026-04-18T00:52:52-0500"
    static let gitHash = "9c93ce9"
    static let gitBranch = "main"
    static let gitDirty = true

    /// One-line human-readable summary, e.g. "build 237 (abc1234*) 2026-04-17".
    /// Asterisk suffix on gitHash indicates a dirty working tree at build time.
    static var summary: String {
        let dirtyMarker = gitDirty ? "*" : ""
        return "build \(buildNumber) (\(gitHash)\(dirtyMarker)) \(buildDate)"
    }
}
