// Auto-generated by generate-build-info.sh — do not edit manually.
// Regenerated on every Xcode build.
enum BuildInfo {
    static let buildNumber = 71
    static let buildDate = "2026-04-17"
    static let gitHash = "809c39c"
}
